-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.numbers')
-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.term')
require('plugins.discord')
require('plugins.nonels')
require('plugins.telescope')
require('plugins.autopairs')
require('plugins.comment')
require('plugins.gitsigns')
require('plugins.flash')
require('plugins.refactoring')
require('plugins.lspsaga')
